sudo: required
language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
services:
- docker
install:
- npm install
script:
- npm test
- docker build -t handmambo/sensor-api .
deploy:
  provider: script
  script: bash bin/docker_push.sh
  on:
    branch: master
env:
  global:
  - secure: dNUoc2sqq1xNozW/4QUuslUd9aolEJiT1eqYSpwrYqgRktTEbREVdXk+IyhdV68jYml067dAFTx7zry5eg9Nuoo0t8/Ye9ySOkuGmDrLnHRs9QgMFhzKKiQTN5+J8xWzhBggrbGS8NATr83eJMuU28pjIDoIqj+L8ToxsEHFD6AFm4JmC+S8NgTtsazOuv8eBYVgzUp5k6E9jACPdYg8X4TIkyogm/J+L/rJvYjlNBI6YgnDeBT8QfMZKLIJzP4st8qK+sV02YeENsGmD4FcBNPx56HHOtM6oG3FU3xSIw4tJMAvPZ0V3BGZnbV56jDSmuO+rG6wRvndK9WoNil1SDkxXDfxoITEG7y1uC89+HfYpdVRJeFQ/CvlWuSoLLMjrNrBZ4myevcjflaahgv0Hs0rwo0ap/lIW0jHIfFKBszZOrgTnZWI8T3xamiktlWxgGTtag7Jc1D734LvqjbYlx0SEJGwMh5bFpsL0lIbqT+JVG9jcGfXbW+akHr4dTkMfaQUiFCUyyfJQYsVs/1epbg3dVvc+KxWd0i7Dx2sq5sVAEJg4Xk9HoamIdM55L3XVxxB0zAdJMAwl9bE/mcBYZk7FfeqOSs66OjoPWbRRgMx0ueF9KYFlGzI5XYB+6cwvhHNEmmjo4xLCF+glmgDEARjeV0uHFbmrdfnrC7LJw4=
  - secure: 3TLiizauDgO5OnxyJIplYQAxDh9wJme8BAN7SkOlnzpTTVbQ0CInfQ7KRaDiFqZOKDQK5R1EKB+6S7V1yrb8IWtzgWkB0zCqpHIYtoy+sLltPt/5gzZj9T6ERK0U5HkmQrBCL7sPEgWc3vSPoSl0lv5Uo5oKMWBMdqRFpMoh3Uzy0c2nmtDGWFY+W/VrWO5w3XffJoaXTpbloc+9dmuIkHKjH65VcWpK5YkM6FSOU7y5dprWgVwDpo60m6r1eonBz/RN6StbSPQTELjdxXIDY8dOTw8J40fFiuIpVdQqifAMluiO87lCBXdjPMQZfWjm0JvfuPdgYRZscDZ2Bu6fmTR/cLUdAViot+yOCWk3VrXWmx5zjjenGd20pODxeGs/n49U31d+RlQy1qaDYlFmBXkTx2uh8anfSJtU1ISsJITu0EsAAM4CBOsu+6ZSlhsRnac/5Q1W4kZ8aF27ERjlPeurnk/p+jB0DmyY0WI4HkQPFrZ5iSkI/HEmQ6amkGcgAqgOjilxqwGqEag/66eZATc/RF4sM/ClqGboL/uz4xsDm7cvfcKx+nbXrSa+c+UqDBB0gQtMCMHcLXeLecF4Js0JDHqVYhJtUQ/R9ugbGkSYekIWl8Ts3Xi3jq3X2zKjs0BEiBmsnFQAP5DHVNRqb0uBOBEyiYE7ZB6HV4sEWeM=
